USE SQLCONSTRAINTS;

SELECT * FROM EMPLOYEEDETAILS;
ALTER TABLE EMPLOYEEDETAILS
DROP COLUMN CITY;
ALTER TABLE EMPLOYEEDETAILS
ADD CITY VARCHAR(20);

UPDATE EMPLOYEEDETAILS SET CITY= 'DELHI' WHERE EID='E0001';
UPDATE EMPLOYEEDETAILS SET CITY= 'PATNA' WHERE EID='E0002';
UPDATE EMPLOYEEDETAILS SET CITY= 'NOIDA' WHERE EID='E0003';
UPDATE EMPLOYEEDETAILS SET CITY= 'UDUPI' WHERE EID='E0004';
UPDATE EMPLOYEEDETAILS SET CITY= 'LUCKNOW' WHERE EID='E0005';
UPDATE EMPLOYEEDETAILS SET CITY= 'DELHI' WHERE EID='E0006';
UPDATE EMPLOYEEDETAILS SET CITY= 'GURGAON' WHERE EID='E0007';
UPDATE EMPLOYEEDETAILS SET CITY= 'DELHI' WHERE EID='E0008';
UPDATE EMPLOYEEDETAILS SET CITY= 'BANGALORE' WHERE EID='E0009';
UPDATE EMPLOYEEDETAILS SET CITY= 'BIHAR' WHERE EID='E0010';

-- CITYWISE COUNT OF EMPLOYEE ARRANGED IN DESCENDING ORDER
SELECT COUNT(EID) AS 'NO OF EMPLOYEE',COUNT(CITY) AS 'CITYWISE' FROM EMPLOYEEDETAILS GROUP BY COUNT(EID);
SELECT * FROM EMPLOYEEDETAILS GROUP BY COUNT(CITY) ORDER BY COUNT(EID);

-- DETAILS OF EMPLOYEES WHO DOESN'T HAVE AN ACCOUNT ON YAHOO DOMAIN.
SELECT * FROM EMPLOYEEDETAILS WHERE EMAIL!='%YAHOO.COM%';

--DESIGNATION WISE TOTAL COST AND NUMBER OF MEMBERS ARRANGED IN DESCENDING ORDER OF THE TOTAL COST.
SELECT * FROM EMPLOYEESALARY;
SELECT DESIG, SUM(SALARY) FROM EMPLOYEESALARY GROUP BY DESIG;-- DESIGNATION WISE TOTAL SALARY
-- BELOW ARE THE DETAILS DESIGNATION WISE TOTAL COST AND NUMBER OF MEMBERS ARRANGED IN DESCENDING ORDER OF THE TOTAL COST.
SELECT DESIG,SUM(SALARY) AS 'TOTAL SAL',COUNT(EID) AS 'NO OF EMPLOYEES' FROM EMPLOYEESALARY GROUP BY DESIG ORDER BY COUNT(EID) DESC;