USE SQLCONSTRAINTS;

-- EID NAME CITY DOJ DESIG SALARY OF THE DELHI EMPLOYEE

SELECT E1.EID,E1.NAME,E1.CITY,E2.DOJ,E2.DESIG,E2.SALARY FROM EMPLOYEEDETAILS E1 INNER JOIN EMPLOYEESALARY E2 ON E1.EID=E2.EID AND CITY='DELHI';

-- DETAILS OF ALL EMPLOYEE WHOSE SALARY DETAILS ARE NOT AVAILABLE

SELECT * FROM EMPLOYEESALARY WHERE SALARY=' ';

-- 

SELECT * FROM EMPLOYEESALARY;
SELECT * FROM EMPLOYEEDETAILS;