USE SQLCONSTRAINTS;

-- EID, NAME, CITY OF GURGEAON OF EMPLOYEES.
SELECT EID,NAME,CITY FROM EMPLOYEEDETAILS WHERE CITY='GURGAON';

-- EID, NAME, DOJ, DEPT, DESIG, AND SALARY OF ALL MANAGER
SELECT EMPLOYEEDETAILS.EID, NAME, DOJ, DEPT, DESIG, SALARY FROM EMPLOYEEDETAILS 
INNER JOIN EMPLOYEESALARY
ON EMPLOYEEDETAILS.EID=EMPLOYEESALARY.EID
WHERE DESIG='MANAGER';

-- REDUCE THE SALARY OF ALL DELHI EMPLOYEES BY 10
--SELECT CITY='DELHI' FROM EMPLOYEEDETAILS WHERE CITY IN (SELECT SALARY=SALARY-(0.10 * SALARY) FROM EMPLOYEESALARY);
SELECT EMPLOYEEDETAILS.CITY,SALARY=SALARY-(0.10 * SALARY) FROM EMPLOYEEDETAILS INNER JOIN EMPLOYEESALARY ON EMPLOYEEDETAILS.EID=EMPLOYEESALARY.EID WHERE CITY='DELHI'; 

-- DISPLAY THE EID, NAME, CITY, DOJ, DEPT, DESIG, SALARY OF THE TEAM MEMBER OF DAVID AND RAMESH GUPTA.
SELECT EMPLOYEEDETAILS.EID,NAME,CITY,DOJ,DEPT,DESIG FROM EMPLOYEEDETAILS
INNER JOIN EMPLOYEESALARY ON EMPLOYEEDETAILS.EID=EMPLOYEESALARY.EID
WHERE (NAME='DAVID' OR NAME='RAMESH GUPTA');

-- CHECK FOR OTHER NAME AS IT IS WORKING CORRECTLY OR NOT
SELECT * FROM EMPLOYEEDETAILS;

SELECT EMPLOYEEDETAILS.EID,NAME,CITY,DOJ,DEPT,DESIG FROM EMPLOYEEDETAILS
INNER JOIN EMPLOYEESALARY ON EMPLOYEEDETAILS.EID=EMPLOYEESALARY.EID
WHERE (NAME='gagan tiwari' OR NAME='surgriv kumar');



USE DEMO_CONSTRAINTS;
-- CREATE A TRAINING TABLE CONTAINING EID, NAME, DEPT, INSERT THE DETAILS OF OPS MEMBERS IN THE TRAINING TABLE.
 CREATE TABLE TRAINING(
 EID CHAR(5),
 NAME VARCHAR(20),
 DEPT VARCHAR(20));

 INSERT INTO TRAINING (EID,NAME,DEPT)
SELECT EMP.EID,NAME,DEPT FROM EMP 
INNER JOIN EMP_SAL
ON EMP.EID=EMP_SAL.EID
WHERE DEPT='OPS';

SELECT * FROM TRAINING;

-- DETAILS OF DIRECTOR SHOULD BE DELETED FROM THE TRAINING TABLE

ALTER TABLE TRAINING
ADD DESIG VARCHAR(20);

UPDATE TRAINING SET DESIG='DIRECTOR'; 

DELETE FROM TRAINING WHERE DESIG='DIRECTOR';

-- DISPLAY THE SALARY DETAILS OF ALL THE EMPLOYEES IF ANY OF THE TEMA MEMBER HAVE SALARY MORE THAN 200000.

SELECT * FROM EMP_SAL WHERE SALARY>200000;