USE INVENTORY;

-- CREATE BELOW PROCEDURES IN THE INVENTORY AS SPECIFIED.
SELECT * FROM ADD_SUP;
/* ADDSUPPLIER - SHOULD ADD THE SUPPLIER IN THE SUPPLIER TABLE AND DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED.*/
CREATE PROCEDURE ADDSUPPLIER @ID AS CHAR(5),@NAM AS VARCHAR(20),@ADR AS VARCHAR(30),@CT AS VARCHAR(15),@PH AS VARCHAR(13),@EML AS VARCHAR(30)
AS BEGIN
	INSERT INTO ADD_SUP 
	VALUES (@ID,@NAM,@ADR,@CT,@PH,@EML);

	SELECT * FROM ADD_SUP;
END;

ADDSUPPLIER 'S0009','AYUSH KUMAR','ASHIYANA ROAD','PATNA','9854761235','AYUSH@WIPRO.CO.IN';

/* ADDPROD- SHOULD ADD THE PRODUCT IN THE PRODUCT TABLE AND DISPLAY THE DETAILS OF NEW PRODUCT ADDED.*/
SELECT * FROM ADD_PROD;

CREATE PROCEDURE ADDPROD @ID AS CHAR(5),@DESC AS VARCHAR(30),@PRC AS INT,@CATGRY AS VARCHAR(30),@SID AS CHAR(5)
AS BEGIN
	INSERT INTO ADD_PROD 
	VALUES (@ID,@DESC,@PRC,@CATGRY,@SID);

	SELECT * FROM ADD_PROD;
END;

ADDPROD 'P0009','SILK CURTAIN',15000,'HOME APPLIANCES','S0009';


/* ADDCUST- SHOULD ADD THE CUSTOMER IN THE CUSTOMER TABLE AND DISPLAY THE DETAILS OF THE NEW CUSTOMER ADDED. */
SELECT * FROM ADD_CUSTOMER;

CREATE PROCEDURE ADDCUST @ID AS CHAR(5),@NAM AS VARCHAR(15),@ADR AS VARCHAR(30),@CT AS VARCHAR(15),@PH AS VARCHAR(13),@EML AS VARCHAR(15),@DB AS DATE
AS BEGIN
	INSERT INTO ADD_CUSTOMER 
	VALUES (@ID,@NAM,@ADR,@CT,@PH,@EML,@DB);

	SELECT * FROM ADD_CUSTOMER;
END;

ADDCUST 'C0005','ASHNEER CHHETI','ROYAL MILEAGE','MUMBAI','8479651245','ASHNEERCH@YAHOO.COM','04-10-1999';
ADDCUST 'C0006','NEHA SHARMA','BAGA BEACH','GOA','8479684756','NEHASHARMA@INDIE.IN','11-28-1989';
ADDCUST 'C0007','AISHWARYA RAI','BHU MOR','VARANSHI','8479654874','AISHWARYARAI@GMAIL.COM','9-19-1957';
ADDCUST 'C0008','RANI MUKHARJEE','DOM PARA','KOLKATA','8479653248','RANIMUKHARJEE@BING.COM','12-21-1999';


/* ADDORDER - SHOULD ADD THE ORDER IN THE ORDERS TABLE AND DISPLAY THE DETAILS OF THE ORDER. ORDER DATE SHOULD BE CURRENT DATE AND SHOULD COME AUTOMATICALLY */


SELECT * FROM ADD_ORD;

CREATE PROCEDURE ADDORDER @ID AS CHAR(5),@DT AS DATE,@P_ID AS CHAR(5),@C_ID AS CHAR(5),@QTY AS INT
AS BEGIN
	INSERT INTO ADD_ORD 
	VALUES (@ID,@DT,@P_ID,@C_ID,@QTY);

	SELECT * FROM ADD_ORD;
END;

ADDORDER 'O0004','01-23-2013','P0004','C0004',300;
