USE INVENTORY;

/* CREATE A FUNCTION FOR AUTOGENERATION OF 5 CHARACTERS ALPHA NUMERIC ID. IT SHOULD ACCEPT 2 PARAMETERS A CHARACTER AND THE RETURN THE ID BY 
CONCATINATING THE CHARACTER, REQUIRED ZEROS, AND THE SPECIFIED NUMBER. */
--###########################################################
CREATE FUNCTION AUTOGENID(@C CHAR(1),@I INT)
RETURNS CHAR(5)
AS 
BEGIN
	DECLARE @R CHAR(5);
	DECLARE @ID CHAR(5);

SELECT @R = CASE 
					WHEN @I < 10 THEN CONCAT(@C,'000')
					WHEN @I < 100 THEN CONCAT (@C,'00')
					WHEN @I < 1000 THEN CONCAT (@C,'0')
					WHEN @I < 10000 THEN @C
					ELSE 'NULL'
		END;
	SET @ID= RTRIM(@R)+LTRIM(CONVERT(CHAR(4),@I));
		RETURN @ID;
	END;
--########################################################################################################
----------------------------------------------------------------------------------------------------------
--########################################################################################################
/* SIMPLER ONE FOR AUTO GENERATE ID */

CREATE FUNCTION	AUTOGENID2 (@C AS CHAR(1), @I AS INT) 
RETURNS CHAR(5)
AS
BEGIN
	DECLARE @ID AS CHAR(5);

	SELECT @ID = CASE
					WHEN @I<10 THEN CONCAT(@C,'000',@I)
					WHEN @I<100 THEN CONCAT(@C,'00',@I)
					WHEN @I<1000 THEN CONCAT(@C,'0',@I)
					WHEN @I<10000 THEN CONCAT(@C,@I)
					ELSE 'NA'
	END;
	RETURN @ID;
END;


/* RECREATE BELOW PROCEDURE IN THE INVENTORY DATABASE AS SPECIFIED (ALL THE IDs SHOULD BE AUTOMATICALLY GENERATED USING ABOVE CREATED FUNCTION 
AND SEQUENCES ) */

-- ADDSUPPLIER - SHOULD ADD THE SUPPLIER IN THE SUPPLIER TABLE AND DISPLAY THE DETAILS OF NEW SUPPLIER ADDED. 

SELECT * FROM ADD_SUP;

CREATE SEQUENCE SUPPSEQ
AS INT
START WITH 1
INCREMENT BY 1;
DROP SEQUENCE SUPPSEQ;
CREATE PROCEDURE ADDSUPPLIER2 @NAM AS VARCHAR(20),@ADR AS VARCHAR(30),@CT AS VARCHAR(15),@PH AS VARCHAR(13),@EML AS VARCHAR(25)
AS BEGIN
		
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);

		SET @I = (NEXT VALUE FOR SUPPSEQ);
		SET @ID = DBO.AUTOGENID2('S',@I);

		INSERT INTO ADD_SUP 
		VALUES (@ID,@NAM,@ADR,@CT,@PH,@EML);

		SELECT * FROM ADD_SUP;
END;

ADDSUPPLIER2 'AKIBA STORE','AKIBA GALI','PUNJI','8471253541','AKIBASTORE@STORE.IN';

ADDSUPPLIER2 'RIDHIMA STORE','SASARAM','VIKALI','7536253541','RIDHIMAFASHIO@STORE.IN';

DELETE FROM ADD_SUP WHERE S_ID='S0005';	


-- ADDPRO - SHOULD ADD THE PRODUCT INT THE PRODUCT TABLE AND DISPLAY THE DETAILS OF NEW PRODUCT ADDED.

SELECT * FROM ADD_PROD;

CREATE SEQUENCE PRODSEQ
AS INT
START WITH 1
INCREMENT BY 1;

CREATE PROCEDURE ADDPRO @DESC AS VARCHAR(20),@PRC AS INT,@CATGRY AS VARCHAR(25) ,@SID AS VARCHAR(13)
AS BEGIN
		
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);

		SET @I = (NEXT VALUE FOR PRODSEQ);
		SET @ID = DBO.AUTOGENID2('P',@I);

		INSERT INTO ADD_PROD 
		VALUES (@ID,@DESC,@PRC,@CATGRY,@SID);

		SELECT * FROM ADD_PROD;
END;

-- INFORMATION TECHNOLOGY
-- HOME APPLIANCES
-- HEALTH CARE
DROP PROCEDURE ADDPRO;
ADDPRO 'VEGETABLE GRINDER',1500,'HOME APPLIANCES','S0007';



-- ADDCUST - SHOULD ADD CUSTOMERS IN THE CUSTOMER TABLE AND DISPLAY THE DETAILS OF NEW CUSTOMER ADDED.

CREATE SEQUENCE CUSTSEQ
AS INT
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE CUSTSEQ;
DROP PROCEDURE ADDCUST;
CREATE PROCEDURE ADDCUST @NAM AS VARCHAR(20),@ADR AS VARCHAR(30),@CT AS VARCHAR(15),@PH AS VARCHAR(13),@EML AS VARCHAR(25),@DB AS DATE 
AS BEGIN
		
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);

		SET @I = (NEXT VALUE FOR CUSTSEQ);
		SET @ID = DBO.AUTOGENID2('C',@I);

		INSERT INTO ADD_CUSTOMER
		VALUES (@ID,@NAM,@ADR,@CT,@PH,@EML,@DB);

		SELECT * FROM ADD_CUSTOMER;
END;

ADDCUST 'ANANYA RAJPUT','ANSUMAN GALI','GOA','8471468741','ANANYARAJPUT@GMAIL.COM','05-05-1997';

ADDSUPPLIER2 'RIDHIMA STORE','SASARAM','VIKALI','7536253541','RIDHIMAFASHIO@STORE.IN';

DELETE FROM ADD_SUP WHERE S_ID='S0005';	



--ADDORDER - SHOULD ADD THE ORDER IN THE ORDER TABLE AND DISPLAY THE DETAILS OF THE ORDER, ORDER DATE SHOULD BE CURRENT DATE 
-- AND SHOULD COME AUTOMATICALLY.

CREATE SEQUENCE ORDSEQ
AS INT
START WITH 1
INCREMENT BY 1;

DROP PROCEDURE ADDORDER;
CREATE PROCEDURE ADDORDER @PID AS CHAR(5),@CID AS CHAR(5),@OQTY AS INT 
AS BEGIN
		
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);
		DECLARE @ODAT AS DATE;
		SET @ODAT=GETDATE();

		SET @I = (NEXT VALUE FOR ORDSEQ);
		SET @ID = DBO.AUTOGENID2('O',@I);
		
		INSERT INTO ADD_ORD
		VALUES (@ID,@ODAT,@PID,@CID,@OQTY);

		SELECT * FROM ADD_ORD WHERE OID=@ID;
END;

ADDORDER 'P0001','C0001',30;

ADDSUPPLIER2 'RIDHIMA STORE','SASARAM','VIKALI','7536253541','RIDHIMAFASHIO@STORE.IN';



