CREATE DATABASE FIRSTDEMO;
USE FIRSTDEMO;

CREATE TABLE STUD
(RNO INT,
NAME VARCHAR(5),
AGE INT);

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (1, 'AJAY', 20);

INSERT INTO STUD
VALUES (2, 'Kash', 21);

INSERT INTO STUD (RNO,NAME)
VALUES (3, 'Kaus'); 
/* HERE WE HAVE NOT GIVEN AGE VALUE , SO FOR MAKE THIS SUCCESSFULL
 YOU HAVE TO SPECIFY AT INSERT TIME WITH HOW MANY COLUMN VALUE YOU ARE GOING TO GIVE. AND THE VALUE WILL STORED AS NULL*/

INSERT INTO STUD (NAME,RNO,AGE)
VALUES ('AMAN',4,33);
/* HERE WE ARE GIVING THE VALUE BUT IN SEQUENCE . SO FOR THAT WE ARE SPECIFYING THE COLUMN NAME AT INSERTING TIME*/

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (5, 'SHYAM', 25);

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (6, 'PARAM', 28);

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (7, 'SONU', 29);

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (8, 'ALI', 30);

INSERT INTO STUD ( RNO, NAME, AGE)
VALUES (9, 'SID', 40);

SELECT RNO, NAME, AGE FROM STUD


/* NOW LETS WORK WITH ANALYTICAL CONDITIONS */
/* ------ 1- WHERE ---------*/
SELECT * FROM STUD
WHERE AGE<30;
/* FINDING AGE BELOW 30 HOW MANY ARE THERE */

/* ------2- LIKE -------------*/
SELECT * FROM STUD
WHERE NAME LIKE 's%';
/* find the name who is starting with 's' */

SELECT * FROM STUD
WHERE NAME LIKE '%m';
/* find the name ending with 'm'*/

SELECT * FROM STUD
WHERE NAME LIKE '%A%';
/* HERE WE ARE FINDING IN THE NAME HOW MANY OF THEM HAVE 'A'.*/

SELECT * FROM STUD
WHERE NAME LIKE '____';
/* HERE UNDERSCORE IS REFER TO NO. OF CHARACTER. 
SO HERE WE ARE FINDING THAT HOW MANY OF NAME IS OF 4 CHARACTER ONLY.
THERE ARE FOUR UNDERSCORE GIVEN AT CONDITION. */

SELECT * FROM STUD
WHERE NAME LIKE '_A%';
/* HERE WE ARE FINDING TO THOSE NAME WHOSE SECOND CHARACTER ARE 'A' */

/* ---------3. TOP --------------*/
SELECT TOP 5 * FROM STUD;
/* HERE WE ARE GETTING TOP 5 DATA BY USING TOP */


/*-------------- UPDATE ---------------------*/
/* HERE COME THE DATA MANUPULATION ----------*/
UPDATE STUD SET AGE=19
WHERE RNO=3;

SELECT * FROM STUD

/* ------------ DELETE --------------------*/
/* ONCE DELETED NEVER BE UNDO --------*/
DELETE FROM STUD
WHERE RNO=3

SELECT * FROM STUD


/* ----------------------ALTER -----------------------------*/
/* ALTER IS BASICALLY USE FOR CREATE A NEW COLUMN, REMOVE A EXISTING COLUMN OR YOU CAN CHAGE THE ATTRIBUTE LIKE SIZE , DATATYPES ETC */

ALTER TABLE STUD
ADD CLASS CHAR(5)
SELECT * FROM STUD;
-- HERE WE HAVE CREATED A NEW COLUMN NAME 'CLASS' BY USING ALTAR

-- IF YOU WANT TO FILL THE DATA IN CLASS COLUMN. YOU CAN DO 
UPDATE STUD SET CLASS='1ST'

SELECT * FROM STUD;

-- IF YOU WANT TO REMOVE THE A COLUMN 

ALTER TABLE STUD
DROP COLUMN CLASS;
SELECT * FROM STUD;
-- HERE WE REMOVE CLASS COLUMN COMPLETELY

INSERT INTO STUD
VALUES (10,'KAMALPREET',25)
/* HERE YOU CAN SEE IT IS SHOWING ERROR "Msg 8152, Level 16, State 14, Line 111 , String or binary data would be truncated.
The statement has been terminated. " . IT MEANS YOU ARE INSERTING VALUE WHICH IS MORE THE GIVEN CHAR (SIZE). 
SO FOR THAT USE ALTER TO UPDATE THE DATATYPE AND ITS SIZE.*/

ALTER TABLE STUD
ALTER COLUMN NAME VARCHAR(15)
SELECT * FROM STUD;
-- HERE WE HAVE CHANGE THE DTYPE OF NAME COLUMN BY USING ALTER.

-- HERE WE WANT TO DELETE A WHOLE TABLE . 
-- DROP TABLE TABLENAME;
-- OR WANTED TO DELETE A WHOLE DATABASE
-- DROP TABLE TABLENAME;